name: random_select
description: Random hero selector for six players with SQLite storage.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
